[build]
  publish = "."

[[headers]]
  for = "/annunci.json"
  [headers.values]
    Cache-Control = "public, max-age=1800"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
